# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:13:03+00:00

from __future__ import annotations

from enum import Enum


class OutputFormat(Enum):
    json = 'json'
    xml = 'xml'


class OutputFormat8(Enum):
    json = 'json'
    xml = 'xml'
    kml = 'kml'
    csv = 'csv'


class SortBy(Enum):
    name = 'name'
    featureType = 'featureType'
    decisionDate = 'decisionDate'


class OutputSRS(Enum):
    integer_4326 = 4326
    integer_4269 = 4269
    integer_3005 = 3005
    integer_3857 = 3857
    integer_26907 = 26907
    integer_26908 = 26908
    integer_26909 = 26909
    integer_26910 = 26910
    integer_26911 = 26911


class Embed(Enum):
    integer_0 = 0
    integer_1 = 1


class OutputStyle(Enum):
    summary = 'summary'
    detail = 'detail'


class ExactSpelling(Enum):
    integer_0 = 0
    integer_1 = 1


class SortBy10(Enum):
    relevance = 'relevance'
    name = 'name'
    featureType = 'featureType'
    decisionDate = 'decisionDate'


class OutputFormat24(Enum):
    json = 'json'
    xml = 'xml'
    kml = 'kml'
    csv = 'csv'
    html = 'html'
